[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "none"
opacity = 0.82
decorations_theme_variant = "Dark"

[window.padding]
x = 18
y = 14

[scrolling]
history = 10000
multiplier = 3

[colors.primary]
background = "#1d2021"
foreground = "#d4be98"

[colors.normal]
black = "#282828"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#928374"

[colors.bright]
black = "#7c6f64"
red = "#f2594b"
green = "#b0b846"
yellow = "#e5b975"
blue = "#8fbcbb"
magenta = "#e0a0b5"
cyan = "#9ac197"
white = "#d4be98"

[colors.selection]
background = "#d4be98"
text = "#1d2021"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.15

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[general]
live_config_reload = true
